<?php

/*
 * This file is licensed under GPLv2+.
*/

/**
 * @file
 * Provides features interacting with weixin public open platform.
 */

define("WEIXIN_SEED_LENGTH",8);

// Define weixin classes
// Constructor: $wee = new WechatRequest($token, $_GET, $wxid);
class WechatRequest
{
	public $wxid = NULL;
	public $msgid = NULL;
	public $username = NULL;
	public $msgtype = NULL;
	public $content = NULL;
	
	public function __construct($token, $args, $wxid) {
		if($this->checkSignature($token, $args)) {
			$this->wxid=$wxid;
		}
	}
	private function checkSignature($token, $get) {
		$signature = $get['signature'];
		$timestamp = $get["timestamp"];
		$nonce = $get["nonce"];
		$tmpArr = array($token, $timestamp, $nonce);
		asort($tmpArr);
		$tmpStr = implode( $tmpArr );
		$tmpStr = sha1( $tmpStr );
		if( $tmpStr == $signature ) return TRUE;
		else return FALSE;
	}
	
	public function pharsePost($post) {
		$postObj = simplexml_load_string($post, 'SimpleXMLElement', LIBXML_NOCDATA);
		if($postObj!= FALSE && $this->wxid == $postObj->ToUserName) {
			$this->username = (string)$postObj->FromUserName;
			$this->msgid = (string)$postObj->MsgId;
			$this->msgtype = (string)$postObj->MsgType;
			switch($this->msgtype) {
				case 'text':
					$this->content = trim((string)$postObj->Content);
					break;
				case 'event':
					if(in_array((string)$postObj->Event, array('subscribe', 'unsubscribe')))
						$this->content = (string)$postObj->Event;
					else
						$this->content = array(
							(string)$postObj->Event => (string)$postObj->EventKey,
						);
					break;
				case 'image':
					$this->content = (string)$postObj->PicUrl;
					break;
				case 'location':
					$this->content = array(
						'longitude' => (string)$postObj->Location_Y,
						'latitude' => (string)$postObj->Location_X,
					);
					break;
				case 'link':
					$this->content = (string)$postObj->Url;
					break;
			}
		}
		unset($postObj);
	}
}

class WechatResponse
{
	private $wxid = NULL;
	private $username = NULL;
	private $requestid = NULL;
	private $type = NULL;
	private $content = NULL;
	private $music = array();
	private $news = array();
	private $stared = 0;
	
	public function __construct($request) {
		if(is_object($request) && get_class($request) == 'WechatRequest') {
			$this->wxid = $request->wxid;
			$this->username = $request->username;
			$this->requestid = $request->msgid;
		}
	}

	public function star($isstared=1) {
		$this->stared = $isstared;
	}

	public function text($content) {
		$this->type = 'text';
		$this->content = $content;
	}

	public function music($title, $description, $url, $hqurl=NULL) {
		if(empty($hqurl)) $hqurl=$url;
		$this->type = 'music';
		$this->music = array(
			'title' => $title,
			'description' => $description,
			'url' => url($url, array('absolute'=>TRUE)),
			'hqurl' => url($hqurl, array('absolute'=>TRUE))
		);
	}

	public function news($items) {
		$this->type = 'news';
		foreach($items as $item) {
			if(empty($item['title'])) continue;
			$this->news[]=array(
				'title'=>$item['title'],
				'description'=>empty($item['description'])?'':$item['description'],
				'picurl'=>url($item['picurl'], array('absolute'=>TRUE)),
				'url'=>url($item['url'], array('absolute'=>TRUE))
			);
		}
	}

	public function __toString() {
		$output = '';
		switch($this->type) {
			case 'text':
				$textTpl = "<xml><ToUserName><![CDATA[%s]]></ToUserName><FromUserName><![CDATA[%s]]></FromUserName><CreateTime>%s</CreateTime><MsgType><![CDATA[%s]]></MsgType><Content><![CDATA[%s]]></Content><FuncFlag>%s</FuncFlag></xml>";
				$output = sprintf($textTpl, $this->username, $this->wxid, time(), 'text', $this->content, $this->stared?1:0);
				break;
			case 'music':
				$textTpl = "<xml><ToUserName><![CDATA[%s]]></ToUserName><FromUserName><![CDATA[%s]]></FromUserName><CreateTime>%s</CreateTime><MsgType><![CDATA[%s]]></MsgType><Music><Title><![CDATA[%s]]></Title><Description><![CDATA[%s]]></Description><MusicUrl><![CDATA[%s]]></MusicUrl><HQMusicUrl><![CDATA[%s]]></HQMusicUrl></Music><FuncFlag>%s</FuncFlag></xml>";
				$output = sprintf($textTpl, $this->username, $this->wxid, time(), 'music',
					$this->music['title'], $this->music['description'], $this->music['url'], $this->music['hqurl'], $this->stared?1:0);
				break;
			case 'news':
				if(count($this->news)<=0) break;
				$news='<Articles>';
				foreach($this->news as $item) {
					$news .= sprintf("<item><Title><![CDATA[%s]]></Title><Description><![CDATA[%s]]></Description><PicUrl><![CDATA[%s]]></PicUrl><Url><![CDATA[%s]]></Url></item>",
						$item['title'], $item['description'], $item['picurl'], $item['url']
					);
				}
				$news.='</Articles>';
				$textTpl = "<xml><ToUserName><![CDATA[%s]]></ToUserName><FromUserName><![CDATA[%s]]></FromUserName><CreateTime>%s</CreateTime><MsgType><![CDATA[%s]]></MsgType><ArticleCount>%s</ArticleCount>%s<FuncFlag>1</FuncFlag></xml>";
				$output = sprintf($textTpl, $this->username, $this->wxid, time(), 'news',
					count($this->news), $news, $this->stared?1:0
				);
				break;
		}
		if(!empty($output)) return $output;
		else return '';
	}
}

/**
 * Implementation of hook_help().
 */
function weixin_help($path, $arg) {
	$output = '';
	switch ($path) {
		case 'admin/config/services/weixin':
			$output = '<p>'.t('In this page, you could set various settings regarding weixin public platform.').'</p>';
			break;
		case 'user/%/weixin':
			$output = '<p>'.t('In this page, you could bind your account with a weixin id, or detach your account from existing weixin id.').'</p>';
			break;
		default:
			return;
	}
	return $output;
}

/**
 * Implementation of hook_permission
 */
function weixin_permission() {
	return array(
		'allow weixin binding' => array(
			'title' => t('Allow binding with weixin account'),
		),
	);
}

/**
 * Implementation of hook_menu().
 */
function weixin_menu() {
	$items['admin/config/services/weixin'] = array(
		'title' => 'weixin rules',
		'description' => 'weixin configuration and customized rules for response.',
		'access arguments' => array('access administration pages'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('weixin_admin_form'),
	);
	$items['weixin'] = array(
		'title' => 'weixin',
		'description' => 'weixin interface',
		'page callback' => 'weixin_response',
		'access callback' => 'weixin_response_access',
		'type' => MENU_CALLBACK,
	);
	$items['user/%user/weixin'] = array(
		'title' => 'Weixin binding',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('weixin_user_binding',1),
		'type' => MENU_LOCAL_TASK,
		'access callback' => 'weixin_user_access',
		'access arguments' => array(1),
	);
	return $items;
}

function weixin_user_access($user) {
	if($user->uid==$GLOBALS['user']->uid) return user_access('allow weixin binding');
	else return user_access('allow weixin binding', $user) && user_access('administer users');
}

function weixin_admin_form($form, $form_state) {
	$form=array(
		'#submit' => array('weixin_admin_form_submit'),
	);
	$form['weixinname'] = array(
		'#type' => 'machine_name',
		'#title' => t('Site global weixin account name'),
		'#description' => t('Weixin account name to display in binding page.'),
		'#default_value' => variable_get('weixinname', ''),
		'#required' => TRUE,
		'#machine_name' => array(
			'exists' => 'weixin_name_fake_exists',
		),
	);
	$form['weixinid'] = array(
		'#type' => 'machine_name',
		'#title' => t('Site global weixin id'),
		'#description' => t('Messages sent to other weixinid will be ignored automatically.'),
		'#default_value' => variable_get('weixinid', ''),
		'#required' => TRUE,
		'#machine_name' => array(
			'exists' => 'weixin_name_fake_exists',
		),
	);
	$form['weixintoken'] = array(
		'#type' => 'textfield',
		'#title' => t('Token'),
		'#description' => t('The token set in weixin public platform.'),
		'#default_value' => variable_get('weixintoken', ''),
		'#required' => TRUE,
	);
	return system_settings_form($form);
}

function weixin_name_fake_exists($value) {
	return FALSE;
}

function weixin_admin_form_submit($form, $form_state) {
	variable_set('weixinname',$form_state['values']['weixinname']);
	variable_set('weixinid',$form_state['values']['weixinid']);
	variable_set('weixintoken',$form_state['values']['weixintoken']);
}

function weixin_response() {
	$wxid=variable_get('weixinid', '');
	$token=variable_get('weixintoken', '');
	$request = new WechatRequest($token, $_GET, $wxid);
	// If connecting to public platform, then echo $_GET['echostr'] and exit.
	if($_SERVER['REQUEST_METHOD']=='GET') {
		watchdog('weixin',
			'Site connected with weixin public platform via @wxid (token @token).',
			array('@wxid' => $wxid, '@token' => $token),
			WATCHDOG_INFO
		);
		drupal_add_http_header('Content-Type', 'text/plain; charset=utf-8');
		echo $_GET['echostr'];
		exit;
	}
	
	// Fill up relative structure
	$request->pharsePost(file_get_contents("php://input"));
	if(!$request->username) exit;
	
	$user=user_load(0);
	$r=db_select('users_weixin','u')->condition('u.wx_openid',$request->username)->condition('u.status',1)->fields('u',array('uid'))->execute()->fetchObject();
	if(isset($r->uid))
		$user=user_load($r->uid);
	$result=implode(module_invoke_all('weixin', $request, $user),'\n');
	drupal_add_http_header('Content-Type', 'application/xml; charset=utf-8');
	if(empty($result)) $result=(($user->uid)?t('Hello @username.',array('@username'=>$user->name)):'').'/:--b'.t('Sorry, but I cannot understand what you are taking about.');

	$resp=new WechatResponse($request);
	$resp->text($result);
	
	watchdog('weixin',
		'Recieved @content and returned @response.',
		array('@content'=>($request->msgid), '@response'=>$result),
		WATCHDOG_DEBUG
	);
	echo $resp;
	exit;
}

function weixin_response_access() {
	$wxid=variable_get('weixinid', '');
	$token=variable_get('weixintoken', '');
	$req = new WechatRequest($token, $_GET, $wxid);
	// If wxid is not set, the the request is invalid.
	return !empty($req->wxid);
}

function weixin_user_binding($form, $form_state, $user) {
	$r=db_select('users_weixin','u')->fields('u')->condition('u.uid',$user->uid)->condition('u.status',1)->countQuery()->execute()->fetchField();
	$form=array();
	$form['user']=array(
		'#type' => 'hidden',
		'#value' => $user->uid,
	);
	// Means it has been bound with
	if($r) { // this user has already bound with weixin account
		$form['description']=array(
			'#type' => 'markup',
			'#markup' => '<p>'.'<img src="'.url(drupal_get_path('module', 'weixin').'/weixin_100.png').'" align="left" width="100" heigh="125" style="padding: 10px"/>'.t('It seems that you have already bound your account with weixin id.').t('If you want to detach your account, please click following button.').'</p>',
		);
		$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Unbound'),
			'#submit' => array('weixin_user_binding_unbound'),
		);
	} else {
		$result=db_select('weixin_validation','w')->condition('uid',$user->uid)->fields('w',array('expiration_time'))->execute();
		if($result->rowCount()==0 || $result->fetchField() < time() ) {
			$seed='';
			$validationcode='';
			$allowable_characters = 'ABCEFHIKLMNPQRSTUVWXYZ';
			$len = strlen($allowable_characters) - 1;
			for($i=0;$i<WEIXIN_SEED_LENGTH;$i++) {
				$seed.=$allowable_characters[mt_rand(0, $len)];
				$validationcode.=$allowable_characters[mt_rand(0, $len)];
			}
			db_delete('weixin_validation')->condition('uid',$user->uid)->execute();
			db_insert('weixin_validation')->fields(array(
				'uid' => $user->uid,
				'seed' => $seed,
				'validation_code' => $validationcode,
				'expiration_time'=> time()+300,
			))->execute();
		}
		$r=db_select('weixin_validation','w')->condition('uid',$user->uid)->fields('w')->execute()->fetchObject();
		$seed=$r->seed;
		$validationcode=$r->validation_code;
		$form['description']=array(
			'#type' => 'markup',
			'#markup' => '<p><img src="'.url(drupal_get_path('module', 'weixin').'/weixin_100.png').'" align="right" width="100" heigh="125" style="padding: 10px"/>'.t('You haven\'t bound your account with weixin id.').t('If you want to bind your account, please do as following.').'</p>',
		);
		$form['step1']=array(
			'#type' => 'item',
			'#title' => '1. '.t('Follow <code>@code</code> in your weixin client',array('@code'=>variable_get('weixinname', ''))),
			'#description' => '<div><img src="'.url(drupal_get_path('module', 'weixin').'/qrcode.jpg').'" valign="top"/>'.t('Scan this qrcode or search <code>@code</code> in your weixin client.', array('@code'=>variable_get('weixinname', ''))).'</div>',
		);
		$form['step2']=array(
			'#type' => 'textfield',
			'#size' => 10,
			'#disabled' => TRUE,
			'#value' => $seed,
			'#title' => '2. '.t('Send following code to <code>@code</code>' ,array('@code'=>variable_get('weixinname', ''))),
			'#description' => t('The code will expire in five minutes. If time passed, please <a href="@url">refresh the page</a>.', array('@url'=>url('user/'.$user->uid.'/weixin'))),
			'#attributes'=>array('style'=>'font-size: 40px'),
		);
		$form['step3']=array(
			'#type' => 'textfield',
			'#required' => TRUE,
			'#size' => 10,
			'#title' => '3. '.t('Enter the validation code here'),
			'#description' => t('Input the validation code you received in your weixin client.'),
			'#attributes'=>array('style'=>'font-size: 40px'),
			'#maxlength'=>WEIXIN_SEED_LENGTH,
		);
		$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Bind my account'),
		);
	}
	
	return $form;
}

function weixin_user_binding_validate($form, &$form_state) {
	if(isset($form_state['values']['step3'])) {
		$result=db_select('users_weixin','u')->condition('status',0)->condition('uid',$form_state['values']['user'])->fields('u')->execute();
		if($result->rowCount()==0) {
			form_set_error('step3', t('It seems that you have not send the message to our weixina public account.')); return;
		}
		$query=db_select('weixin_validation','w')->condition('seed',$form_state['values']['step2'])->fields('w');
		$result=$query->execute();
		switch($result->rowCount()) {
			case 0:
				$form_state['rebuild']=true; break;
			case 1:
				$r=$result->fetchObject();
				if($r->validation_code != strtoupper($form_state['values']['step3'])) {
					form_set_error('step3', t('The validation code you have entered is wrong.')); break;
				}
		}
	}
}

function weixin_user_binding_submit($form, &$form_state) {
	$user=user_load($form_state['values']['user']);
	db_update('users_weixin')->condition('uid',$form_state['values']['user'])->condition('status',0)->fields(array(
		'status'=>1,
	))->execute();
	db_delete('weixin_validation')->condition('uid',$user->uid)->execute();
	$r=db_select('users_weixin','u')->condition('uid',$user->uid)->fields('u',array('wx_openid'))->execute()->fetchField();
	watchdog('weixin',
		'@username bound his account with weixin id @wxid.',
		array('@username'=>$user->name, '@wxid'=>$r),
		WATCHDOG_INFO
	);
	drupal_set_message(t('Weixin acccount bound successfully.'));
}

function weixin_user_binding_unbound($form, $form_state) {
	$user=user_load($form_state['values']['user']);
	db_delete('users_weixin')->condition('uid',$user->uid)->execute();
	watchdog('weixin',
		'@user detached his weixin account.',
		array('@user'=>$user->name),
		WATCHDOG_INFO
	); 
	drupal_set_message(t('Weixin acccount detached.'));
}

function weixin_weixin($request, $user) {
	// If welcome message should be displayed:
	if($request->msgtype=='event' && $request->content=='subscribe') {
		$t=t('Welcome to @sitename. You are talking with robot now.',array('@sitename'=>variable_get('site_name')));
	}
	// If user unsubscribe the account, then we should remove related records.
	if($request->msgtype=='event' && $request->content=='unsubscribe') {
		db_delete('users_weixin')->condition('wx_openid',$request->username)->execute();
		watchdog('weixin',
			'User @username unsubscribed the account.',
			array('@username'=>$user->name),
			WATCHDOG_DEBUG
		); 
	}
	$content=trim($request->content);
	// If sent given number of ucase chars, then validate it.
	if($request->msgtype=='text' && preg_match('/^[A-Z]{'.WEIXIN_SEED_LENGTH.'}$/',$content)) {
		$r=db_select('weixin_validation','w')->fields('w')->condition('seed',$content)->execute()->fetchObject();
		if($r) {
			// Lets check if the users have been registered with another account at first
			$c=db_select('users_weixin','u')->condition('wx_openid',$request->username)->fields('u')->countQuery()->execute()->fetchField();
			if($c>0)
				$t=t('Sorry, you have already registered with another account at @sitename.', array('@sitename'=>variable_get('site_name')));
			else if($r->expiration_time < time())
				$t=t('The code you have entered has expired. Please fresh the page.');
			else {
				$t=t('Your validation code is @code, please input it at website.', array('@code' => $r->validation_code));
				db_delete('users_weixin')->condition('uid',$r->uid)->execute();
				db_insert('users_weixin')->fields(array(
					'uid' => $r->uid,
					'wx_openid' => $request->username,
					'status' => 0,
				))->execute();
			}
		}
	}
	// If user want to unbound the weixin account, then do it.
	if($request->msgtype=='text' && preg_match('/'.t('Unbound').'/',$content)) {
		db_delete('users_weixin')->condition('uid',$user->uid)->execute();
		$t=t('@username has been unbound with your weixin account.', array('@username'=>$user->name));
		watchdog('weixin',
			'@username unbound his account with weixin.',
			array('@username'=>$user->name),
			WATCHDOG_DEBUG
		); 
	}

	if(isset($t)) return $t;
}

function weixin_is_wechat_browser() {
	return preg_match('/ MicroMessenger\//', $_SERVER['HTTP_USER_AGENT']);
}

function weixin_cron() {
	db_delete('weixin_validation')->condition('expiration_time',time(),'<')->execute();
}

/**
 *  * Implementation of hook_uninstall().
 *   */
function weixin_uninstall() {
	$settings=array(
		'weixinname', 'weixinid', 'weixintoken'
	);
	foreach($settings as $s) {
		variable_del($s);
	}
}

